# Generated by Django 3.2.7 on 2021-10-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0004_movie_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='genre',
        ),
    ]
