# Generated by Django 3.2.7 on 2021-10-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0005_rename_movie_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
