# Generated by Django 3.2.7 on 2021-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0009_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='hollymovies_app.Movie'),
        ),
    ]
