# Generated by Django 3.2.8 on 2021-10-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0011_rename_actors_actor_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': {('can_like_movie', 'Can like movie')}},
        ),
    ]
